# Generated by Django 5.0.4 on 2024-04-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_project_id'),
    ]

    operations = [
        
        
        migrations.AlterField(
            model_name='project',
            name='NAME_Project',
            field=models.CharField(max_length=50, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='TYPE_Project',
            field=models.CharField(max_length=50, verbose_name='项目类型'),
        ),
    ]
