# Generated by Django 3.2.25 on 2024-05-05 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_project_cur_project_project_mana_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='CUR_Project',
            field=models.CharField(max_length=50, verbose_name='货币单位'),
        ),
        migrations.AlterField(
            model_name='project',
            name='END_Project',
            field=models.CharField(max_length=20, verbose_name='项目结束时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='START_Project',
            field=models.CharField(max_length=20, verbose_name='项目开始时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='VALUE_Project',
            field=models.CharField(default='', max_length=50, verbose_name='项目价值'),
        ),
        migrations.CreateModel(
            name='ProjectNode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NAME_Milestone', models.CharField(max_length=100)),
                ('DDL_Milestone', models.DateField()),
                ('DES_Milestone', models.CharField(blank=True, max_length=1000, null=True)),
                ('PHEN_Milestone', models.CharField(max_length=10)),
                ('ID_Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='app01.project')),
            ],
        ),
    ]
