# Generated by Django 3.2.25 on 2024-05-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20240505_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='CUR_Project',
            field=models.CharField(max_length=50, verbose_name='货币单位'),
        ),
    ]
