# Generated by Django 3.2.25 on 2024-05-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_project_cur_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectnode',
            name='ID_Project',
        ),
    ]
