# Generated by Django 3.2.25 on 2024-05-05 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_remove_projectnode_id_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectnode',
            name='ID_Project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='app01.project'),
        ),
    ]
