# Generated by Django 3.2.25 on 2024-05-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_projectnode_id_project'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='projectnode',
            name='ID_Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='app01.project'),
        ),
    ]
