# Generated by Django 3.2.25 on 2024-05-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20240507_0300'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='projectnode',
            name='DDL_Milestone',
            field=models.CharField(max_length=20),
        ),
    ]
