# Generated by Django 3.2.25 on 2024-05-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20240507_0602'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='projectnode',
            name='DDL_Milestone',
            field=models.DateField(),
        ),
    ]
