# Generated by Django 3.2.25 on 2024-05-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20240507_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='MANA_Project',
            field=models.CharField(default='', max_length=20, verbose_name='项目负责人'),
        ),
    ]
