# Generated by Django 3.2.25 on 2024-05-07 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_project_mana_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NAME_Person', models.CharField(max_length=20)),
                ('NUM_Person', models.CharField(max_length=50)),
                ('MAIL_Person', models.CharField(max_length=50)),
                ('POS_Person', models.CharField(max_length=10)),
                ('DESC_Person', models.CharField(blank=True, max_length=1000, null=True)),
                ('ID_Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='app01.project')),
            ],
        ),
    ]
