# Generated by Django 3.2.25 on 2024-05-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('file_format', models.CharField(max_length=20)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
