# Generated by Django 3.2.25 on 2024-05-14 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ID_Project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='app01.project'),
        ),
    ]
