# Generated by Django 3.2.25 on 2024-05-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_file_id_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='FILE',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_format',
            new_name='FORM_File',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='NAME_File',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='size',
            new_name='SIZE_File',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='upload_time',
            new_name='UPTIME_File',
        ),
    ]
