# Generated by Django 3.2.25 on 2024-05-27 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_auto_20240521_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityInspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME_Qit', models.CharField(max_length=20)),
                ('ID_Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_templates', to='app01.project')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME_Item', models.CharField(max_length=20)),
                ('VALUE_Item', models.CharField(max_length=30)),
                ('ID_Qit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_items', to='app01.qualityinspectiontemplate')),
            ],
        ),
    ]
