# Generated by Django 3.2.25 on 2024-05-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_securitycheckitem_securitychecktemplate_securityissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityissue',
            name='ATTACH_Issue',
        ),
        migrations.AddField(
            model_name='securityissue',
            name='ID_Project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='SIssue', to='app01.project'),
        ),
        migrations.AddField(
            model_name='securityissue',
            name='PHEN_Issue',
            field=models.CharField(default='未解决', max_length=20),
        ),
        migrations.CreateModel(
            name='SecurityIssueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='security_images/')),
                ('security_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app01.securityissue')),
            ],
        ),
    ]
