# Generated by Django 3.2.25 on 2024-06-05 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_auto_20240531_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyIssueSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE_Solution', models.DateField(verbose_name='解决日期')),
                ('DESCRIPTION_Solution', models.CharField(max_length=5000, verbose_name='解决方案')),
                ('ID_Report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='app01.securityinspectionreport')),
            ],
        ),
        migrations.CreateModel(
            name='CostInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME_Cost', models.CharField(max_length=100, verbose_name='成本名称')),
                ('TYPE_Expense', models.CharField(max_length=50, verbose_name='费用类型')),
                ('BUDGET_Amount', models.CharField(max_length=20, verbose_name='预算金额')),
                ('UNIT_Currency', models.CharField(max_length=10, verbose_name='货币单位')),
                ('DESC_Cost', models.CharField(blank=True, max_length=500, null=True, verbose_name='描述')),
                ('DATE_Cost', models.DateField(verbose_name='日期')),
                ('NAME_Accountant', models.CharField(max_length=50, verbose_name='财务人员')),
                ('COST_Amount', models.CharField(blank=True, max_length=20, null=True, verbose_name='成本金额')),
                ('ID_Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.project', verbose_name='所属项目')),
            ],
        ),
    ]
