# Generated by Django 3.2.25 on 2024-06-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_costinformation_safetyissuesolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NAME_USER', models.CharField(max_length=100, verbose_name='用户名称')),
                ('PASSWORD', models.CharField(max_length=100, verbose_name='用户密码')),
                ('LEVEL', models.CharField(max_length=100, verbose_name='用户级别')),
            ],
        ),
    ]
