# Generated by Django 5.0.4 on 2026-05-02 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LegacyUser',
        ),
        migrations.AlterModelOptions(
            name='legacyuser',
            options={'verbose_name': '旧用户表', 'verbose_name_plural': '旧用户表'},
        ),
        migrations.AddField(
            model_name='person',
            name='sys_role',
            field=models.CharField(choices=[('admin', '系统管理员'), ('project_manager', '项目管理员'), ('member', '普通成员')], default='member', max_length=20, verbose_name='系统角色'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联登录账号'),
        ),
    ]
