# Generated by Django 5.0.4 on 2026-05-11 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='UPLOADER_Person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='app01.person', verbose_name='上传人'),
        ),
    ]
