# Generated by Django 5.0.4 on 2026-08-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0026_file_index_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='INDEX_ERROR_DETAIL_File',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='INDEX_ERROR_TYPE_File',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='INDEX_STAGE_File',
            field=models.CharField(choices=[('idle', '空闲'), ('queued', '任务已排队'), ('prepare', '准备任务'), ('cleanup', '清理旧索引'), ('parse', '解析文件'), ('split', '切分文本'), ('qdrant_connect', '连接向量库'), ('embedding', '生成向量'), ('qdrant_upsert', '写入向量库'), ('elasticsearch_index', '写入关键词索引'), ('delete_vectors', '删除向量索引'), ('completed', '任务完成'), ('failed', '任务失败')], default='idle', max_length=50),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['INDEX_STAGE_File'], name='file_idx_stage'),
        ),
    ]
