# Generated by Django 5.0.4 on 2026-08-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_backfill_file_index_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='INDEX_MAX_RETRIES_File',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='file',
            name='INDEX_NEXT_RETRY_AT_File',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='INDEX_RETRYABLE_File',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='INDEX_RETRY_COUNT_File',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='INDEX_STAGE_File',
            field=models.CharField(choices=[('idle', '空闲'), ('queued', '任务已排队'), ('prepare', '准备任务'), ('retry_wait', '等待重试'), ('cleanup', '清理旧索引'), ('parse', '解析文件'), ('split', '切分文本'), ('qdrant_connect', '连接向量库'), ('embedding', '生成向量'), ('qdrant_upsert', '写入向量库'), ('elasticsearch_index', '写入关键词索引'), ('delete_vectors', '删除向量索引'), ('completed', '任务完成'), ('failed', '任务失败')], default='idle', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='INDEX_STATUS_File',
            field=models.CharField(choices=[('not_indexed', '未入库'), ('queued', '排队中'), ('running', '入库中'), ('retrying', '正在重试'), ('completed', '已入库'), ('failed', '入库失败'), ('deleting', '删除中')], default='not_indexed', max_length=20),
        ),
    ]
