# Generated by Django 5.0.4 on 2026-09-01 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0030_file_index_cancelled_at_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='新的文档问答', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_chat_sessions', to='app01.person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_chat_sessions', to='app01.project')),
            ],
            options={
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RagChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=20)),
                ('content', models.TextField()),
                ('sources_json', models.JSONField(blank=True, default=list)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app01.ragchatsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='ragchatsession',
            index=models.Index(fields=['project', 'owner', '-updated_at'], name='rag_sess_project_owner'),
        ),
        migrations.AddIndex(
            model_name='ragchatsession',
            index=models.Index(fields=['project', '-last_message_at'], name='rag_sess_project_last'),
        ),
        migrations.AddIndex(
            model_name='ragchatmessage',
            index=models.Index(fields=['session', 'created_at'], name='rag_msg_session_time'),
        ),
    ]
