# Generated by Django 5.0.4 on 2026-09-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0031_ragchatsession_ragchatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragchatsession',
            name='memory_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ragchatsession',
            name='summarized_message_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ragchatsession',
            name='summary_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
