"""
Django settings for Projectmanagement project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from kombu import Exchange, Queue

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(env_path):
    """Load simple KEY=VALUE pairs from a local .env file without extra dependencies."""
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-local-dev-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "app01.apps.App01Config",
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'app01.middleware.PerformanceLogMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]

X_FRAME_OPTIONS = 'ALLOWALL'

CORS_ALLOW_ALL_ORIGINS = True
# 允许跨域请求时发送 cookies
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000'
)
CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:3000'
)
# 允许跨域请求的 HTTP 方法
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# 允许跨域请求的 HTTP 头
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# 配置媒体文件路径
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

ROOT_URLCONF = 'Projectmanagement.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Projectmanagement.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DB_CONN_MAX_AGE = int(os.getenv('DB_CONN_MAX_AGE', '60'))
DB_CONN_HEALTH_CHECKS = env_bool('DB_CONN_HEALTH_CHECKS', True)
DB_CONNECT_TIMEOUT = int(os.getenv('DB_CONNECT_TIMEOUT', '5'))
DB_READ_TIMEOUT = int(os.getenv('DB_READ_TIMEOUT', '30'))
DB_WRITE_TIMEOUT = int(os.getenv('DB_WRITE_TIMEOUT', '30'))

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME', 'project_management'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'CONN_MAX_AGE': DB_CONN_MAX_AGE,
        'CONN_HEALTH_CHECKS': DB_CONN_HEALTH_CHECKS,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'connect_timeout': DB_CONNECT_TIMEOUT,
            'read_timeout': DB_READ_TIMEOUT,
            'write_timeout': DB_WRITE_TIMEOUT,
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Celery / Redis
# Redis is used as the broker and result backend for long-running work such as
# file indexing, OCR, embedding, and future report jobs. Keeping these jobs out
# of request threads is the first step toward stable multi-user concurrency.
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0'))
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', os.getenv('REDIS_RESULT_URL', 'redis://127.0.0.1:6379/1'))
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = os.getenv('CELERY_TIMEZONE', 'UTC')
CELERY_TASK_TRACK_STARTED = True
CELERY_WORKER_PREFETCH_MULTIPLIER = int(os.getenv('CELERY_WORKER_PREFETCH_MULTIPLIER', '1'))
CELERY_TASK_ACKS_LATE = env_bool('CELERY_TASK_ACKS_LATE', True)
CELERY_TASK_TIME_LIMIT = int(os.getenv('CELERY_TASK_TIME_LIMIT', '1800'))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv('CELERY_TASK_SOFT_TIME_LIMIT', '1500'))
CELERY_TASK_DEFAULT_QUEUE = os.getenv('CELERY_TASK_DEFAULT_QUEUE', 'default')
CELERY_RAG_INDEX_QUEUE = os.getenv('CELERY_RAG_INDEX_QUEUE', 'rag_index')
CELERY_RAG_MAINTENANCE_QUEUE = os.getenv('CELERY_RAG_MAINTENANCE_QUEUE', 'rag_maintenance')
CELERY_MONITORED_QUEUES = env_list(
    'CELERY_MONITORED_QUEUES',
    f'{CELERY_TASK_DEFAULT_QUEUE},{CELERY_RAG_INDEX_QUEUE},{CELERY_RAG_MAINTENANCE_QUEUE}',
)
CELERY_TASK_DEFAULT_EXCHANGE = CELERY_TASK_DEFAULT_QUEUE
CELERY_TASK_DEFAULT_ROUTING_KEY = CELERY_TASK_DEFAULT_QUEUE
CELERY_TASK_CREATE_MISSING_QUEUES = True
CELERY_TASK_QUEUES = (
    Queue(CELERY_TASK_DEFAULT_QUEUE, Exchange(CELERY_TASK_DEFAULT_QUEUE), routing_key=CELERY_TASK_DEFAULT_QUEUE),
    Queue(CELERY_RAG_INDEX_QUEUE, Exchange(CELERY_RAG_INDEX_QUEUE), routing_key=CELERY_RAG_INDEX_QUEUE),
    Queue(CELERY_RAG_MAINTENANCE_QUEUE, Exchange(CELERY_RAG_MAINTENANCE_QUEUE), routing_key=CELERY_RAG_MAINTENANCE_QUEUE),
)
CELERY_TASK_ROUTES = {
    'app01.tasks.celery_health_check': {
        'queue': CELERY_TASK_DEFAULT_QUEUE,
        'routing_key': CELERY_TASK_DEFAULT_QUEUE,
    },
    'app01.tasks.rag_index_file_task': {
        'queue': CELERY_RAG_INDEX_QUEUE,
        'routing_key': CELERY_RAG_INDEX_QUEUE,
    },
    'app01.tasks.rag_delete_file_vectors_task': {
        'queue': CELERY_RAG_MAINTENANCE_QUEUE,
        'routing_key': CELERY_RAG_MAINTENANCE_QUEUE,
    },
    'app01.tasks.rag_finalize_file_index_cancel_task': {
        'queue': CELERY_RAG_MAINTENANCE_QUEUE,
        'routing_key': CELERY_RAG_MAINTENANCE_QUEUE,
    },
}
CELERY_RAG_INDEX_RATE_LIMIT = os.getenv('CELERY_RAG_INDEX_RATE_LIMIT', '')
if CELERY_RAG_INDEX_RATE_LIMIT:
    CELERY_TASK_ANNOTATIONS = {
        'app01.tasks.rag_index_file_task': {
            'rate_limit': CELERY_RAG_INDEX_RATE_LIMIT,
        },
    }
RAG_INDEX_MAX_RETRIES = int(os.getenv('RAG_INDEX_MAX_RETRIES', '3'))
RAG_INDEX_RETRY_BASE_DELAY = int(os.getenv('RAG_INDEX_RETRY_BASE_DELAY', '30'))
RAG_INDEX_RETRY_MAX_DELAY = int(os.getenv('RAG_INDEX_RETRY_MAX_DELAY', '300'))

# Redis cache
CACHE_URL = os.getenv('CACHE_URL', 'redis://127.0.0.1:6379/2')
CACHE_KEY_PREFIX = os.getenv('CACHE_KEY_PREFIX', 'projectmanage')
CACHE_DEFAULT_TIMEOUT = int(os.getenv('CACHE_DEFAULT_TIMEOUT', '300'))
API_CACHE_ENABLED = env_bool('API_CACHE_ENABLED', True)
API_CACHE_TTL_PROJECT_LIST = int(os.getenv('API_CACHE_TTL_PROJECT_LIST', '60'))
API_CACHE_TTL_PROJECT_DETAIL = int(os.getenv('API_CACHE_TTL_PROJECT_DETAIL', '60'))
API_CACHE_TTL_PROJECT_NODES = int(os.getenv('API_CACHE_TTL_PROJECT_NODES', '30'))
API_CACHE_TTL_PROJECT_PERSONS = int(os.getenv('API_CACHE_TTL_PROJECT_PERSONS', '60'))
API_CACHE_TTL_PROJECT_COSTS = int(os.getenv('API_CACHE_TTL_PROJECT_COSTS', '30'))
API_CACHE_TTL_PROJECT_FILES = int(os.getenv('API_CACHE_TTL_PROJECT_FILES', '10'))
API_DEFAULT_PAGE_SIZE = int(os.getenv('API_DEFAULT_PAGE_SIZE', '50'))
API_MAX_PAGE_SIZE = int(os.getenv('API_MAX_PAGE_SIZE', '100'))

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': CACHE_URL,
        'KEY_PREFIX': CACHE_KEY_PREFIX,
        'TIMEOUT': CACHE_DEFAULT_TIMEOUT,
    }
}

# Performance logging
# Enabled by default in local DEBUG mode. It forces Django SQL query logging only
# for selected API paths so load tests can expose slow requests and N+1 queries.
PERF_LOG_ENABLED = env_bool('PERF_LOG_ENABLED', DEBUG)
PERF_SLOW_REQUEST_MS = int(os.getenv('PERF_SLOW_REQUEST_MS', '500'))
PERF_SLOW_QUERY_MS = int(os.getenv('PERF_SLOW_QUERY_MS', '100'))
PERF_QUERY_WARN_COUNT = int(os.getenv('PERF_QUERY_WARN_COUNT', '30'))
PERF_LOG_SAMPLE_RATE = float(os.getenv('PERF_LOG_SAMPLE_RATE', '1.0'))
PERF_LOG_PATH_PREFIXES = tuple(env_list(
    'PERF_LOG_PATH_PREFIXES',
    '/projects/,/files/,/login/,/csrf/',
))

# Elasticsearch
ELASTICSEARCH_URL = os.getenv('ELASTICSEARCH_URL', 'http://127.0.0.1:9200')
ELASTICSEARCH_INDEX = os.getenv('ELASTICSEARCH_INDEX', 'project_file_chunks')
AUDIT_LOG_ES_INDEX = os.getenv('AUDIT_LOG_ES_INDEX', 'project_audit_logs')

# 向量库 Qdrant
QDRANT_URL = os.getenv('QDRANT_URL', 'http://127.0.0.1:6333')
QDRANT_VECTOR_SIZE = int(os.getenv('QDRANT_VECTOR_SIZE', '2560'))
LANGCHAIN_QDRANT_COLLECTION = os.getenv('LANGCHAIN_QDRANT_COLLECTION', 'project_files_langchain_qwen3_4b')

# 本地 Embedding 模型
EMBEDDING_PROVIDER = os.getenv('EMBEDDING_PROVIDER', 'llama_cpp')
EMBEDDING_BASE_URL = os.getenv('EMBEDDING_BASE_URL', 'http://127.0.0.1:8080/v1')
EMBEDDING_MODEL = os.getenv('EMBEDDING_MODEL', 'Qwen3-Embedding-4B-GGUF')
EMBEDDING_BATCH_SIZE = int(os.getenv('EMBEDDING_BATCH_SIZE', '8'))
VECTOR_UPSERT_BATCH_SIZE = int(os.getenv('VECTOR_UPSERT_BATCH_SIZE', '16'))

# RAG 回答模型
RAG_CHAT_BASE_URL = os.getenv('RAG_CHAT_BASE_URL', 'https://dashscope.aliyuncs.com/compatible-mode/v1')
RAG_CHAT_API_KEY = os.getenv('DASHSCOPE_API_KEY', '')
RAG_CHAT_MODEL = os.getenv('RAG_CHAT_MODEL', 'qwen3.7-flash')
RAG_CHAT_TIMEOUT = int(os.getenv('RAG_CHAT_TIMEOUT', '45'))
RAG_CHAT_RATE_LIMIT_ENABLED = env_bool('RAG_CHAT_RATE_LIMIT_ENABLED', True)
RAG_CHAT_RATE_WINDOW_SECONDS = int(os.getenv('RAG_CHAT_RATE_WINDOW_SECONDS', '60'))
RAG_CHAT_USER_RATE_LIMIT_PER_MINUTE = int(os.getenv('RAG_CHAT_USER_RATE_LIMIT_PER_MINUTE', '12'))
RAG_CHAT_PROJECT_RATE_LIMIT_PER_MINUTE = int(os.getenv('RAG_CHAT_PROJECT_RATE_LIMIT_PER_MINUTE', '60'))
RAG_CHAT_GLOBAL_RATE_LIMIT_PER_MINUTE = int(os.getenv('RAG_CHAT_GLOBAL_RATE_LIMIT_PER_MINUTE', '120'))
RAG_CHAT_USER_MAX_IN_FLIGHT = int(os.getenv('RAG_CHAT_USER_MAX_IN_FLIGHT', '2'))
RAG_CHAT_GLOBAL_MAX_IN_FLIGHT = int(os.getenv('RAG_CHAT_GLOBAL_MAX_IN_FLIGHT', '8'))
RAG_CHAT_IN_FLIGHT_TTL = int(os.getenv('RAG_CHAT_IN_FLIGHT_TTL', '300'))
RAG_CHAT_HISTORY_MAX_MESSAGES = int(os.getenv('RAG_CHAT_HISTORY_MAX_MESSAGES', '10'))
RAG_CHAT_RECENT_MESSAGES = int(os.getenv('RAG_CHAT_RECENT_MESSAGES', str(RAG_CHAT_HISTORY_MAX_MESSAGES)))
RAG_CHAT_SUMMARY_MAX_MESSAGES = int(os.getenv('RAG_CHAT_SUMMARY_MAX_MESSAGES', '70'))
RAG_CHAT_SUMMARY_TRIGGER_MESSAGES = int(os.getenv('RAG_CHAT_SUMMARY_TRIGGER_MESSAGES', str(RAG_CHAT_RECENT_MESSAGES)))
RAG_CHAT_SUMMARY_UPDATE_INTERVAL_MESSAGES = int(os.getenv('RAG_CHAT_SUMMARY_UPDATE_INTERVAL_MESSAGES', '4'))
RAG_CHAT_SUMMARY_SOURCE_MESSAGE_CHARS = int(os.getenv('RAG_CHAT_SUMMARY_SOURCE_MESSAGE_CHARS', '500'))
RAG_CHAT_SUMMARY_MAX_CHARS = int(os.getenv('RAG_CHAT_SUMMARY_MAX_CHARS', '2500'))
RAG_MULTI_QUERY_ENABLED = env_bool('RAG_MULTI_QUERY_ENABLED', True)
RAG_MULTI_QUERY_COUNT = int(os.getenv('RAG_MULTI_QUERY_COUNT', '3'))
RAG_MULTI_QUERY_RECALL_LIMIT = int(os.getenv('RAG_MULTI_QUERY_RECALL_LIMIT', '30'))
RAG_MULTI_QUERY_MAX_QUERY_CHARS = int(os.getenv('RAG_MULTI_QUERY_MAX_QUERY_CHARS', '180'))
RAG_RERANK_CANDIDATE_LIMIT = int(os.getenv('RAG_RERANK_CANDIDATE_LIMIT', '32'))
RAG_MODEL_RERANK_CANDIDATE_LIMIT = int(os.getenv('RAG_MODEL_RERANK_CANDIDATE_LIMIT', '24'))
RAG_CONTEXT_COMPRESSION_ENABLED = env_bool('RAG_CONTEXT_COMPRESSION_ENABLED', True)
RAG_CONTEXT_COMPRESSION_CANDIDATE_LIMIT = int(os.getenv('RAG_CONTEXT_COMPRESSION_CANDIDATE_LIMIT', '16'))
RAG_CONTEXT_COMPRESSION_MIN_KEEP_ITEMS = int(os.getenv('RAG_CONTEXT_COMPRESSION_MIN_KEEP_ITEMS', '6'))
RAG_CONTEXT_COMPRESSION_MAX_ITEM_CHARS = int(os.getenv('RAG_CONTEXT_COMPRESSION_MAX_ITEM_CHARS', '900'))
RAG_CONTEXT_COMPRESSION_MAX_SENTENCES = int(os.getenv('RAG_CONTEXT_COMPRESSION_MAX_SENTENCES', '6'))
RAG_CONTEXT_COMPRESSION_SENTENCE_WINDOW = int(os.getenv('RAG_CONTEXT_COMPRESSION_SENTENCE_WINDOW', '1'))
RAG_CONTEXT_COMPRESSION_DROP_UNMATCHED_AFTER_MIN_KEEP = env_bool(
    'RAG_CONTEXT_COMPRESSION_DROP_UNMATCHED_AFTER_MIN_KEEP',
    False,
)
RAG_LLM_CONTEXT_COMPRESSION_ENABLED = env_bool('RAG_LLM_CONTEXT_COMPRESSION_ENABLED', True)
RAG_LLM_CONTEXT_COMPRESSION_MODEL = os.getenv('RAG_LLM_CONTEXT_COMPRESSION_MODEL', RAG_CHAT_MODEL)
RAG_LLM_CONTEXT_COMPRESSION_CANDIDATE_LIMIT = int(os.getenv('RAG_LLM_CONTEXT_COMPRESSION_CANDIDATE_LIMIT', '5'))
RAG_LLM_CONTEXT_COMPRESSION_MIN_ITEM_CHARS = int(os.getenv('RAG_LLM_CONTEXT_COMPRESSION_MIN_ITEM_CHARS', '350'))
RAG_LLM_CONTEXT_COMPRESSION_MAX_ITEM_CHARS = int(os.getenv('RAG_LLM_CONTEXT_COMPRESSION_MAX_ITEM_CHARS', '700'))
RAG_CONTEXT_COMPRESSION_CIRCUIT_FAILURE_THRESHOLD = int(os.getenv('RAG_CONTEXT_COMPRESSION_CIRCUIT_FAILURE_THRESHOLD', '2'))
RAG_CONTEXT_COMPRESSION_CIRCUIT_OPEN_SECONDS = int(os.getenv('RAG_CONTEXT_COMPRESSION_CIRCUIT_OPEN_SECONDS', '60'))
RAG_CIRCUIT_BREAKER_ENABLED = env_bool('RAG_CIRCUIT_BREAKER_ENABLED', True)
RAG_CHAT_MODEL_CIRCUIT_FAILURE_THRESHOLD = int(os.getenv('RAG_CHAT_MODEL_CIRCUIT_FAILURE_THRESHOLD', '3'))
RAG_CHAT_MODEL_CIRCUIT_OPEN_SECONDS = int(os.getenv('RAG_CHAT_MODEL_CIRCUIT_OPEN_SECONDS', '60'))
RAG_RERANK_CIRCUIT_FAILURE_THRESHOLD = int(os.getenv('RAG_RERANK_CIRCUIT_FAILURE_THRESHOLD', '3'))
RAG_RERANK_CIRCUIT_OPEN_SECONDS = int(os.getenv('RAG_RERANK_CIRCUIT_OPEN_SECONDS', '60'))

# RAG Rerank 模型
RAG_RERANK_BASE_URL = os.getenv(
    'RAG_RERANK_BASE_URL',
    'https://dashscope.aliyuncs.com/api/v1/services/rerank/text-rerank/text-rerank',
)
RAG_RERANK_API_KEY = os.getenv('DASHSCOPE_API_KEY', '')
RAG_RERANK_MODEL = os.getenv('RAG_RERANK_MODEL', 'qwen3-rerank')
RAG_RERANK_TIMEOUT = int(os.getenv('RAG_RERANK_TIMEOUT', '30'))
RAG_RERANK_INSTRUCT = os.getenv(
    'RAG_RERANK_INSTRUCT',
    'Given a web search query, retrieve relevant passages that answer the query.',
)


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'app01.performance': {
            'handlers': ['console'],
            'level': os.getenv('PERF_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'app01.cache': {
            'handlers': ['console'],
            'level': os.getenv('CACHE_LOG_LEVEL', 'WARNING'),
            'propagate': False,
        },
        'app01.rag_resilience': {
            'handlers': ['console'],
            'level': os.getenv('RAG_RESILIENCE_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}
