"""
Django settings for Projectmanagement project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(env_path):
    """Load simple KEY=VALUE pairs from a local .env file without extra dependencies."""
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-local-dev-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "app01.apps.App01Config",
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]

X_FRAME_OPTIONS = 'ALLOWALL'

CORS_ALLOW_ALL_ORIGINS = True
# 允许跨域请求时发送 cookies
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000'
)
CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:3000'
)
# 允许跨域请求的 HTTP 方法
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# 允许跨域请求的 HTTP 头
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# 配置媒体文件路径
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

ROOT_URLCONF = 'Projectmanagement.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Projectmanagement.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME', 'project_management'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
    }
}

# Elasticsearch
ELASTICSEARCH_URL = os.getenv('ELASTICSEARCH_URL', 'http://127.0.0.1:9200')
ELASTICSEARCH_INDEX = os.getenv('ELASTICSEARCH_INDEX', 'project_file_chunks')
AUDIT_LOG_ES_INDEX = os.getenv('AUDIT_LOG_ES_INDEX', 'project_audit_logs')

# 向量库 Qdrant
QDRANT_URL = os.getenv('QDRANT_URL', 'http://127.0.0.1:6333')
QDRANT_VECTOR_SIZE = int(os.getenv('QDRANT_VECTOR_SIZE', '2560'))
LANGCHAIN_QDRANT_COLLECTION = os.getenv('LANGCHAIN_QDRANT_COLLECTION', 'project_files_langchain_qwen3_4b')

# 本地 Embedding 模型
EMBEDDING_PROVIDER = os.getenv('EMBEDDING_PROVIDER', 'llama_cpp')
EMBEDDING_BASE_URL = os.getenv('EMBEDDING_BASE_URL', 'http://127.0.0.1:8080/v1')
EMBEDDING_MODEL = os.getenv('EMBEDDING_MODEL', 'Qwen3-Embedding-4B-GGUF')

# RAG 回答模型
RAG_CHAT_BASE_URL = os.getenv('RAG_CHAT_BASE_URL', 'https://dashscope.aliyuncs.com/compatible-mode/v1')
RAG_CHAT_API_KEY = os.getenv('DASHSCOPE_API_KEY', '')
RAG_CHAT_MODEL = os.getenv('RAG_CHAT_MODEL', 'qwen3.6-plus')

# RAG Rerank 模型
RAG_RERANK_BASE_URL = os.getenv(
    'RAG_RERANK_BASE_URL',
    'https://dashscope.aliyuncs.com/compatible-api/v1',
)
RAG_RERANK_API_KEY = os.getenv('DASHSCOPE_API_KEY', '')
RAG_RERANK_MODEL = os.getenv('RAG_RERANK_MODEL', 'qwen3-rerank')
RAG_RERANK_TIMEOUT = int(os.getenv('RAG_RERANK_TIMEOUT', '30'))
RAG_RERANK_INSTRUCT = os.getenv(
    'RAG_RERANK_INSTRUCT',
    'Given a web search query, retrieve relevant passages that answer the query.',
)


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
